import test from 'node:test';
import assert from 'node:assert/strict';
import {stepVehicle,blocked,waterAt,missionTick,MISSIONS,safeLoad} from '../src/simulation.js';
test('forward drive and right turn follow vehicle heading',()=>{const c={x:0,z:60,angle:Math.PI,speed:0};for(let i=0;i<60;i++)stepVehicle(c,{throttle:1,steer:0,brake:false},1/60,[]);assert.ok(c.z<52);for(let i=0;i<30;i++)stepVehicle(c,{throttle:1,steer:1,brake:false},1/60,[]);assert.ok(c.x>1);});
test('brake stops the car and reverse is capped',()=>{const c={x:0,z:100,angle:0,speed:30};for(let i=0;i<120;i++)stepVehicle(c,{throttle:0,steer:0,brake:true},1/60,[]);assert.ok(c.speed<.05);for(let i=0;i<180;i++)stepVehicle(c,{throttle:-1,steer:0,brake:false},1/60,[]);assert.ok(c.speed>=-11&&c.speed<0);});
test('water, buildings, and map edge block movement',()=>{assert.equal(waterAt(100,-100),true);assert.equal(blocked(29,-100,2,[]),true);assert.equal(blocked(0,25,2,[]),false);assert.equal(blocked(294,0,2,[]),true);const c={x:0,z:10,angle:Math.PI,speed:20};const r=stepVehicle(c,{throttle:1,steer:0,brake:false},.05,[{x:0,z:5,w:8,d:6}]);assert.equal(r.collided,true);assert.equal(c.z,10);});
test('every mission progresses in order and completes only once',()=>{for(let i=0;i<MISSIONS.length;i++){const run={index:i,stop:0,active:true,remaining:150};for(let j=0;j<MISSIONS[i].stops.length;j++){assert.equal(missionTick(run,MISSIONS[i].stops[j],.016),j===MISSIONS[i].stops.length-1?'complete':'checkpoint');}assert.equal(run.active,false);assert.equal(missionTick(run,MISSIONS[i].stops.at(-1),1),null);}});
test('mission fails at expiry without granting completion',()=>{const run={index:0,stop:0,active:true,remaining:.01};assert.equal(missionTick(run,MISSIONS[0].stops[0],.02),'failed');assert.equal(run.stop,0);});
test('save loading survives denied storage and corrupt data',()=>{assert.equal(safeLoad({getItem(){throw Error();}}).cash,0);assert.equal(safeLoad({getItem:()=>'{no'}).cash,0);const v=safeLoad({getItem:()=>JSON.stringify({cash:-10,completed:[0,1,45,'2'],quality:'bad'})});assert.deepEqual(v,{cash:0,completed:[0,1],quality:'auto'});});
