import './style.css';
import * as THREE from 'three';
import {createWorld,makeCar,makePerson} from './world.js';
import {MISSIONS,clamp,distance,angleDelta,blocked,stepVehicle,missionTick,safeLoad} from './simulation.js';

const $=id=>document.getElementById(id);
let save;try{save=safeLoad(localStorage);}catch{save={cash:0,completed:[],quality:'auto'};}
function persist(){try{localStorage.setItem('valley-run-save',JSON.stringify(save));}catch{/* Private browsing can disable storage. Play remains available. */}}
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:false,powerPreference:'high-performance'});}catch{ $('loading').innerHTML='<h2>Unable to start 3D</h2><p>This game needs WebGL. Try Safari or Chrome with hardware acceleration enabled.</p>';throw new Error('WebGL unavailable');}
renderer.setClearColor('#b1c3ad');renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));
const scene=new THREE.Scene();scene.background=new THREE.Color('#b1c3ad');scene.fog=new THREE.Fog('#b1c3ad',120,560);
scene.add(new THREE.HemisphereLight('#e5f1d9','#61735a',2.6));
const sun=new THREE.DirectionalLight('#ffddb0',2.2);sun.position.set(-90,150,80);scene.add(sun);
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.3,850);
const world=createWorld(scene);
const car={x:0,z:-8,angle:Math.PI,speed:0,health:100,mesh:makeCar(),name:'HIMALAYAN 4×4',autonomous:false};scene.add(car.mesh);
const cars=[car];
const route=[{x:-240,z:120},{x:-240,z:-240},{x:0,z:-240},{x:0,z:240},{x:-240,z:240}];
for(let i=0;i<7;i++){const p=route[i%route.length];const v={x:p.x+(i>4?5:0),z:p.z+(i>4?35:0),angle:0,speed:0,health:100,mesh:makeCar(['#b77b59','#cad0b4','#567f79','#bba562','#8195a0'][i%5]),name:i%2?'VALLEY TAXI':'TOWN RUNNER',autonomous:true,waypoint:(i+1)%route.length};scene.add(v.mesh);cars.push(v);}
const walker=makePerson('#b9a17c');walker.visible=false;scene.add(walker);
let currentCar=car,walking=false,player={x:car.x,z:car.z,angle:car.angle};
const pedestrians=[];for(let i=0;i<18;i++){const p=makePerson(['#927f62','#79948a','#b08e6c','#626f66'][i%4]);const z=-210+i*23;p.position.set(i%2?13:-14,0,z);scene.add(p);pedestrians.push({mesh:p,base:z,phase:i});}
const marker=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(5.2,.18,5,40),new THREE.MeshBasicMaterial({color:'#ffce72'}));ring.rotation.x=Math.PI/2;ring.position.y=.45;marker.add(ring);
const beam=new THREE.Mesh(new THREE.CylinderGeometry(2.8,5.2,12,12,1,true),new THREE.MeshBasicMaterial({color:'#ffcf79',transparent:true,opacity:.12,side:THREE.DoubleSide,depthWrite:false}));beam.position.y=6;marker.add(beam);
const diamond=new THREE.Mesh(new THREE.OctahedronGeometry(.95),new THREE.MeshBasicMaterial({color:'#ffda8e'}));diamond.position.y=8;marker.add(diamond);scene.add(marker);
const shadow=new THREE.Mesh(new THREE.PlaneGeometry(3.4,5.7),new THREE.MeshBasicMaterial({color:'#243d2c',transparent:true,opacity:.3,depthWrite:false}));shadow.rotation.x=-Math.PI/2;scene.add(shadow);
let selected=0,run={active:false,index:0,stop:0,remaining:0},heat=0,lastCrash=-100,gameTime=0,paused=false,camMode=0,toastUntil=0,bustTime=0,collisionCooldown=0,uiClock=0;
let police=null,hasMoved=false;
const keys=new Set(),touch={x:0,y:0,brake:false};
function toast(text,duration=3.5){$('toast').textContent=text;$('toast').classList.add('visible');toastUntil=gameTime+duration;}
function soundTone(freq=660,duration=.1){if(!audio.enabled)return;const o=audio.ctx.createOscillator(),g=audio.ctx.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.045,audio.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.ctx.currentTime+duration);o.connect(g).connect(audio.ctx.destination);o.start();o.stop(audio.ctx.currentTime+duration);}
const audio={enabled:false,ctx:null,engine:null,gain:null};
function toggleAudio(){if(!audio.ctx){audio.ctx=new(window.AudioContext||window.webkitAudioContext)();audio.engine=audio.ctx.createOscillator();audio.gain=audio.ctx.createGain();audio.engine.type='triangle';audio.gain.gain.value=0;audio.engine.connect(audio.gain).connect(audio.ctx.destination);audio.engine.start();}audio.ctx.resume();audio.enabled=!audio.enabled;$('sound').style.color=audio.enabled?'#f6ca72':'';$('sound').setAttribute('aria-label',audio.enabled?'Mute sound':'Enable sound');toast(audio.enabled?'Engine audio on':'Audio muted');}
function updateMissionUI(){const m=MISSIONS[selected];$('mission-title').textContent=m.title;$('mission-description').textContent=m.description;$('mission-tag').textContent=m.type;$('reward').textContent=`₹ ${m.reward.toLocaleString()}`;document.querySelector('.chapter').textContent=`0${selected+1} / 03`;$('start-mission').hidden=run.active;$('start-mission').style.display=run.active?'none':'flex';$('mission-progress').hidden=!run.active;$('mission-toggle').textContent=run.active?'Mission options':'Browse missions';document.body.classList.toggle('playing',run.active||hasMoved);}
function startMission(index=selected){selected=index;run={active:true,index,stop:0,remaining:MISSIONS[index].time};closeMenu();updateMissionUI();toast(MISSIONS[index].stops[0].label+' · follow the gold marker');soundTone();}
function closeMenu(){$('menu').close();paused=false;keys.clear();touch.x=0;touch.y=0;touch.brake=false;}
function showMenu(html){keys.clear();touch.x=0;touch.y=0;touch.brake=false;paused=true;$('menu-content').innerHTML=html;if(!$('menu').open)$('menu').showModal();}
function missionMenu(){showMenu(`<span class="menu-kicker">JOBS AROUND THE VALLEY</span><h2>Small jobs. Open roads.</h2><p>Reach the gold marker to collect a job, then follow it to your destination. Jobs can be replayed.</p>${MISSIONS.map((m,i)=>`<div class="menu-row"><div><strong>${save.completed.includes(i)?'✓ ':''}${m.title}</strong><small>${m.type} · ₹ ${m.reward} · ${m.time} seconds</small></div><button data-job="${i}">${run.active&&run.index===i?'Restart':'Drive'}</button></div>`).join('')}${run.active?'<div class="menu-buttons"><button id="cancel-job">Abandon mission</button></div>':''}`);document.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>startMission(Number(b.dataset.job)));if($('cancel-job'))$('cancel-job').onclick=()=>{run.active=false;updateMissionUI();closeMenu();toast('Mission abandoned. The valley is still yours.');};}
function pauseMenu(){showMenu(`<span class="menu-kicker">TAKE A BREATHER</span><h2>The valley can wait.</h2><p>Your game is paused. Earnings and completed jobs save automatically on this device.</p><div class="menu-row"><div><strong>Rendering quality</strong><small>Auto adapts resolution to frame rate.</small></div><select id="quality" aria-label="Rendering quality"><option value="auto">Auto</option><option value="low">Battery saver</option><option value="high">High</option></select></div><div class="menu-buttons"><button id="resume">Back to the valley</button><button id="recover">Recover vehicle · free</button></div><p>Phone: open this game over HTTPS in Safari or Chrome, then use Add to Home Screen / Install app. Landscape gives you a wider view.</p>`);$('quality').value=save.quality;$('quality').onchange=e=>{save.quality=e.target.value;applyQuality();persist();};$('resume').onclick=closeMenu;$('recover').onclick=()=>{recover();closeMenu();};}
function guide(){showMenu(`<span class="menu-kicker">THE VALLEY FIELD GUIDE</span><h2>Rooted in Kashmir.</h2><p>An original, stylised autumn drive through a condensed fictional valley. The geography is compressed for play; these are inspirations, not exact replicas.</p><div class="menu-row"><div><strong>Dal Lake & the boulevard</strong><small>Shikaras, houseboat verandas, a stone promenade, and chinar trees.</small></div></div><div class="menu-row"><div><strong>Srinagar’s old town</strong><small>Timber-framed brick homes, pitched roofs, lattice windows and craft deliveries.</small></div></div><div class="menu-row"><div><strong>Pampore-inspired fields</strong><small>Purple saffron crocuses on cultivated plots, paired with an autumn palette.</small></div></div><h3>How to play</h3><p>WASD / arrows: drive or walk. Space: brake. E: exit or enter a nearby vehicle. C: change camera. M: missions. Escape: pause. On mobile, push the left stick up to accelerate, down to reverse, and sideways to steer. Use EXIT / ENTER and BRAKE on the right.</p><p>Collisions raise heat. Create distance from the pursuit car and drive cleanly to lose it. If caught, you lose up to ₹ 150. Recover your vehicle free in the pause menu.</p><p>Research: <a href="https://kashmirtourismofficial.com/dal-lake.html" target="_blank" rel="noreferrer">Dal Lake</a> · <a href="https://kashmirtourismofficial.com/nishat-bagh.html" target="_blank" rel="noreferrer">Nishat Bagh</a> · <a href="https://www.unesco.org/en/creative-cities/srinagar" target="_blank" rel="noreferrer">Srinagar crafts</a> · <a href="https://iiim.res.in/saffron-production/" target="_blank" rel="noreferrer">Kashmir saffron</a>. Full research notes are included with the source.</p>`);}
function recover(message='Back on the boulevard. Vehicle repaired.'){
  currentCar=car;walking=false;walker.visible=false;car.x=0;car.z=-8;car.angle=Math.PI;car.speed=0;car.health=100;car.autonomous=false;player={x:car.x,z:car.z,angle:car.angle};heat=0;bustTime=0;if(police){scene.remove(police.mesh);police=null;}if(run.active){run.active=false;updateMissionUI();}toast(message);$('touch-action').textContent='EXIT';
}
function interact(){
  if(paused)return;
  if(!walking){if(Math.abs(currentCar.speed)>3){toast('Slow down before stepping out.');return;}let position=null;for(const offset of [-3.5,3.5]){const x=currentCar.x+Math.cos(currentCar.angle)*offset,z=currentCar.z-Math.sin(currentCar.angle)*offset;if(!blocked(x,z,.5,world.obstacles)){position={x,z};break;}}if(!position){toast('No room to exit here. Move onto the road.');return;}currentCar.speed=0;walking=true;player={...position,angle:currentCar.angle};walker.visible=true;$('touch-action').textContent='ENTER';toast('On foot · walk near a vehicle and press E to enter');
  }else{const nearest=cars.filter(c=>distance(c,player)<6).sort((a,b)=>distance(a,player)-distance(b,player))[0];if(!nearest){toast('Walk closer to a vehicle to enter.');return;}currentCar=nearest;currentCar.autonomous=false;currentCar.speed=0;walking=false;walker.visible=false;$('touch-action').textContent='EXIT';toast(currentCar.name+' · ready to go');}
}
function addHeat(impact){if(collisionCooldown>0)return;collisionCooldown=1.2;currentCar.health=Math.max(0,currentCar.health-impact*.55);heat=clamp(heat+1,0,3);lastCrash=gameTime;soundTone(110,.2);toast(heat===1?'Watch the bodywork. Lose the heat by driving cleanly.':'Heat rising. Keep moving and create distance.');if(currentCar.health<=0)recover('Vehicle recovered. Your active mission was cancelled.');}
function updateTraffic(dt){for(const v of cars){if(v.autonomous&&v!==currentCar){const dest=route[v.waypoint];if(distance(v,dest)<6)v.waypoint=(v.waypoint+1)%route.length;const target=route[v.waypoint];const desired=Math.atan2(target.x-v.x,target.z-v.z);v.angle+=clamp(angleDelta(v.angle,desired),-dt*2,dt*2);v.speed=distance(v,player)<9?2:8;v.x+=Math.sin(v.angle)*v.speed*dt;v.z+=Math.cos(v.angle)*v.speed*dt;}v.mesh.position.set(v.x,0,v.z);v.mesh.rotation.y=v.angle;for(const wheel of v.mesh.userData.wheels)wheel.rotation.x+=v.speed*dt*1.8;}}
// Road-graph pursuit avoids blindly steering through buildings or the lake.
const nodes=[];for(const x of [-240,-120,0])for(const z of [-240,-120,0,120,240])nodes.push({x,z});
function nearestNode(p){let best=0;for(let i=1;i<nodes.length;i++)if(distance(p,nodes[i])<distance(p,nodes[best]))best=i;return best;}
function roadPath(a,b){const start=nearestNode(a),end=nearestNode(b),queue=[[start]],seen=new Set([start]);while(queue.length){const path=queue.shift(),last=path.at(-1);if(last===end)return path.map(i=>nodes[i]);for(let i=0;i<nodes.length;i++)if(!seen.has(i)&&distance(nodes[last],nodes[i])===120){seen.add(i);queue.push([...path,i]);}}return [];}
function pursuit(dt){if(!heat)return;if(!police){let n=nodes[nearestNode(player)];police={x:n.x,z:n.z,angle:0,mesh:makeCar('#425d55',true),path:[],reroute:0};if(distance(police,player)<40)police.z=clamp(police.z+80,-280,280);scene.add(police.mesh);}
  police.reroute-=dt;if(police.reroute<=0){police.path=roadPath(police,player);if(police.path.length&&distance(police,police.path[0])<8)police.path.shift();police.reroute=3;}
  if(police.path.length&&distance(police,police.path[0])<6)police.path.shift();let target=police.path[0]||player;
  if(distance(police,player)<35&&(Math.abs(police.x-player.x)<10||Math.abs(police.z-player.z)<10))target=player;
  police.angle+=clamp(angleDelta(police.angle,Math.atan2(target.x-police.x,target.z-police.z)),-dt*2.8,dt*2.8);
  let nx=police.x+Math.sin(police.angle)*(12+heat*2)*dt,nz=police.z+Math.cos(police.angle)*(12+heat*2)*dt;if(!blocked(nx,nz,1.7,world.obstacles)){police.x=nx;police.z=nz;}else police.reroute=0;
  police.mesh.position.set(police.x,0,police.z);police.mesh.rotation.y=police.angle;
  if(distance(police,player)<6){bustTime+=dt;if(!walking)currentCar.speed*=Math.exp(-dt*2);if(bustTime>2.5){save.cash=Math.max(0,save.cash-150);persist();recover('Caught! Up to ₹ 150 paid. Back on the boulevard.');}}else bustTime=0;
  if(gameTime-lastCrash>13&&police&&distance(police,player)>45){heat-=1;lastCrash=gameTime-5;if(!heat){scene.remove(police.mesh);police=null;toast('Heat cleared. Enjoy the open road.');}}
}
function tick(dt){gameTime+=dt;collisionCooldown-=dt;if(gameTime>toastUntil)$('toast').classList.remove('visible');const throttle=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-touch.y;const steer=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+touch.x;const brake=keys.has('Space')||touch.brake;
  if(Math.abs(throttle)+Math.abs(steer)>.1&&!hasMoved){hasMoved=true;updateMissionUI();}
  if(walking){let dx=steer,dz=-throttle,len=Math.hypot(dx,dz);if(len>.1){dx/=Math.max(1,len);dz/=Math.max(1,len);const nx=player.x+dx*6*dt,nz=player.z+dz*6*dt;if(!blocked(nx,nz,.5,world.obstacles)){player.x=nx;player.z=nz;}player.angle=Math.atan2(dx,dz);}walker.position.set(player.x,Math.sin(gameTime*15)*.025*(len>.1),player.z);walker.rotation.y=player.angle;
  }else{const result=stepVehicle(currentCar,{throttle:clamp(throttle,-1,1),steer:clamp(steer,-1,1),brake},dt,world.obstacles);if(result.collided)addHeat(result.impact);player.x=currentCar.x;player.z=currentCar.z;player.angle=currentCar.angle;for(const v of cars)if(v!==currentCar&&distance(v,currentCar)<3.6&&Math.abs(currentCar.speed)>4){addHeat(Math.abs(currentCar.speed));currentCar.speed*=-.4;}}
  updateTraffic(dt);pursuit(dt);
  const outcome=missionTick(run,player,dt);if(outcome==='complete'){const m=MISSIONS[run.index];save.cash+=m.reward;if(!save.completed.includes(run.index))save.completed.push(run.index);persist();toast(`Job complete! + ₹ ${m.reward} · ${save.completed.length} / 3 jobs completed`,6);soundTone(880,.25);selected=(selected+1)%MISSIONS.length;updateMissionUI();}else if(outcome==='checkpoint'){toast(MISSIONS[run.index].stops[run.stop].label);soundTone(700,.15);}else if(outcome==='failed'){toast('Time’s up. Try the job again from the mission menu.',5);updateMissionUI();}
  const target=run.active?MISSIONS[run.index].stops[run.stop]:MISSIONS[selected].stops[0];marker.position.set(target.x,0,target.z);diamond.rotation.y=gameTime;diamond.position.y=8+Math.sin(gameTime*2)*.6;ring.scale.setScalar(1+Math.sin(gameTime*2)*.04);
  world.boats.forEach((b,i)=>{b.position.y=Math.sin(gameTime*.7+i)*.08;b.rotation.z=Math.sin(gameTime*.5+i)*.015;});pedestrians.forEach(p=>{p.mesh.position.z=p.base+Math.sin(gameTime*.2+p.phase)*7;p.mesh.rotation.y=Math.cos(gameTime*.2+p.phase)>0?0:Math.PI;});
  shadow.visible=!walking;shadow.position.set(currentCar.x,.25,currentCar.z);shadow.rotation.z=-currentCar.angle;
  if(audio.ctx){audio.gain.gain.setTargetAtTime(audio.enabled&&!walking?.016+Math.abs(currentCar.speed)*.00045:0,audio.ctx.currentTime,.1);audio.engine.frequency.setTargetAtTime(45+Math.abs(currentCar.speed)*3,audio.ctx.currentTime,.1);}
  uiClock+=dt;if(uiClock>.1){uiClock=0;updateHUD(target);drawMap($('minimap'));}
}
function district(){if(player.z>178)return 'SAFFRON FIELDS';if(player.x<-70)return 'OLD TOWN';if(player.z<-205)return 'GARDEN ROAD';if(player.x>60)return 'ORCHARD QUARTER';return 'DAL LAKE';}
function updateHUD(target){const speed=walking?0:Math.round(Math.abs(currentCar.speed)*3.6);$('speed').textContent=String(speed).padStart(2,'0');$('gear').textContent=walking?'—':currentCar.speed<-.5?'R':speed<1?'N':String(Math.min(5,1+Math.floor(speed/25)));$('speed-fill').style.width=speed/126*100+'%';$('condition-fill').style.width=currentCar.health+'%';$('vehicle-name').textContent=walking?'EXPLORING ON FOOT':currentCar.name;$('wallet').textContent='₹ '+save.cash.toLocaleString();$('heat').textContent='★ '.repeat(heat)+'☆ '.repeat(3-heat);$('heat').setAttribute('aria-label',`Pursuit heat ${heat} of 3`);$('district').textContent=$('map-district').textContent=district();$('mission-distance').textContent=Math.round(distance(player,target))+' m away';if(run.active){$('objective').textContent=target.label;$('timer').textContent=`${String(Math.floor(run.remaining/60)).padStart(2,'0')}:${String(Math.ceil(run.remaining%60)).padStart(2,'0')}`;}$('clock').textContent=`16:${String(42+Math.floor(gameTime/60)%18).padStart(2,'0')}`;}
function drawMap(canvas,large=false){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.fillStyle='#273e35';ctx.fillRect(0,0,w,h);const scale=large?w/680:w/410;const cx=large?0:player.x,cz=large?0:player.z;
  const px=x=>(x-cx)*scale+w/2,pz=z=>(z-cz)*scale+h/2;ctx.fillStyle='#416e67';ctx.fillRect(px(30),pz(-335),305*scale,304*scale);ctx.fillStyle='#688154';ctx.fillRect(px(45),pz(-296),135*scale,44*scale);ctx.fillStyle='#6d5b6b';ctx.fillRect(px(35),pz(193),190*scale,45*scale);ctx.strokeStyle='#758174';ctx.lineWidth=9*scale;for(const x of [-240,-120,0]){ctx.beginPath();ctx.moveTo(px(x),pz(-300));ctx.lineTo(px(x),pz(300));ctx.stroke();}for(const z of [-240,-120,0,120,240]){ctx.beginPath();ctx.moveTo(px(-300),pz(z));ctx.lineTo(px(z<0?12:300),pz(z));ctx.stroke();}for(const x of [120,240]){ctx.beginPath();ctx.moveTo(px(x),pz(25));ctx.lineTo(px(x),pz(300));ctx.stroke();}
  ctx.fillStyle='#4b5849';for(const o of world.obstacles)ctx.fillRect(px(o.x-o.w/2),pz(o.z-o.d/2),o.w*scale,o.d*scale);
  const target=run.active?MISSIONS[run.index].stops[run.stop]:MISSIONS[selected].stops[0];let tx=clamp(px(target.x),9,w-9),tz=clamp(pz(target.z),9,h-9);ctx.strokeStyle='#f1c57355';ctx.lineWidth=1;ctx.setLineDash([3,4]);ctx.beginPath();ctx.moveTo(px(player.x),pz(player.z));ctx.lineTo(tx,tz);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#f6ca72';ctx.save();ctx.translate(tx,tz);ctx.rotate(Math.PI/4);ctx.fillRect(-4,-4,8,8);ctx.restore();if(police){ctx.fillStyle='#df806d';ctx.beginPath();ctx.arc(px(police.x),pz(police.z),3,0,7);ctx.fill();}
  if(large){ctx.font='11px sans-serif';ctx.fillStyle='#bdcbb4';for(const [text,x,z]of[['OLD TOWN',-205,-55],['DAL LAKE',120,-160],['SAFFRON FIELDS',55,268],['GARDENS',84,-300]])ctx.fillText(text,px(x),pz(z));}
  ctx.save();ctx.translate(px(player.x),pz(player.z));ctx.rotate(-player.angle);ctx.fillStyle='#fff8df';ctx.shadowColor='#fff5cf';ctx.shadowBlur=8;ctx.beginPath();ctx.moveTo(0,7);ctx.lineTo(-4,-5);ctx.lineTo(0,-2);ctx.lineTo(4,-5);ctx.closePath();ctx.fill();ctx.restore();
}
function mapMenu(){showMenu('<span class="menu-kicker">YOUR CORNER OF KASHMIR</span><h2>Take the long way.</h2><p>Gold: current objective · white: you · red: pursuit. The dotted line shows direction, not a road route.</p><canvas id="large-map" width="560" height="560" aria-label="Full valley map"></canvas>');drawMap($('large-map'),true);}
const camPos=new THREE.Vector3(),look=new THREE.Vector3(),smoothLook=new THREE.Vector3(player.x,1,player.z-10);
function updateCamera(dt,initial=false){const ratio=innerWidth/innerHeight;const extra=ratio<.8?1.3:1;if(camMode===0){camPos.set(player.x-26*extra,18*extra,player.z+32*extra);look.set(player.x,2,player.z-13);}else if(camMode===1){camPos.set(player.x-Math.sin(player.angle)*24,13,player.z-Math.cos(player.angle)*24);look.set(player.x+Math.sin(player.angle)*12,1,player.z+Math.cos(player.angle)*12);}else{camPos.set(player.x+1,88,player.z+42);look.set(player.x,0,player.z);}const alpha=initial?1:1-Math.exp(-dt*4);camera.position.lerp(camPos,alpha);smoothLook.lerp(look,alpha);camera.lookAt(smoothLook);}
function applyQuality(){const base=save.quality==='low'?1:save.quality==='high'?2:1.5;renderer.setPixelRatio(Math.min(devicePixelRatio,base));renderer.setSize(innerWidth,innerHeight,false);}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();applyQuality();renderer.render(scene,camera);}addEventListener('resize',resize);resize();updateCamera(0,true);
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Escape'){e.preventDefault();$('menu').open?closeMenu():pauseMenu();return;}if(paused)return;keys.add(e.code);if(e.code==='KeyE')interact();if(e.code==='KeyM')missionMenu();if(e.code==='KeyC'){camMode=(camMode+1)%3;toast(['Scenic camera','Chase camera','Overhead camera'][camMode]);}});
addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();touch.x=touch.y=0;touch.brake=false;});document.addEventListener('visibilitychange',()=>{keys.clear();touch.x=touch.y=0;touch.brake=false;if(document.hidden){if(!$('menu').open)pauseMenu();if(audio.gain)audio.gain.gain.value=0;}});
let joyId=null;const joy=$('joystick');function moveJoy(e){if(e.pointerId!==joyId)return;const r=joy.getBoundingClientRect(),max=r.width*.31;let x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,len=Math.hypot(x,y);if(len>max){x*=max/len;y*=max/len;}touch.x=Math.abs(x/max)>.12?x/max:0;touch.y=Math.abs(y/max)>.12?y/max:0;$('stick').style.transform=`translate(${x}px,${y}px)`;}
joy.onpointerdown=e=>{joyId=e.pointerId;joy.setPointerCapture(e.pointerId);moveJoy(e);};joy.onpointermove=moveJoy;function releaseJoy(){joyId=null;touch.x=touch.y=0;$('stick').style.transform='';}joy.onpointerup=releaseJoy;joy.onpointercancel=releaseJoy;joy.onlostpointercapture=releaseJoy;
$('touch-brake').onpointerdown=e=>{touch.brake=true;e.currentTarget.setPointerCapture(e.pointerId);};for(const event of ['pointerup','pointercancel','lostpointercapture'])$('touch-brake').addEventListener(event,()=>touch.brake=false);$('touch-action').onclick=interact;
$('camera-toggle').onclick=()=>{if(!paused){camMode=(camMode+1)%3;toast(['Scenic camera','Chase camera','Overhead camera'][camMode]);}};
$('start-mission').onclick=()=>startMission();$('mission-toggle').onclick=missionMenu;$('pause').onclick=pauseMenu;$('help').onclick=guide;$('sound').onclick=toggleAudio;$('map-expand').onclick=mapMenu;document.querySelector('.brand').onclick=e=>{e.preventDefault();pauseMenu();};document.querySelector('.close').onclick=closeMenu;$('menu').addEventListener('cancel',e=>{e.preventDefault();closeMenu();});
let last=performance.now(),frameCount=0,frameTime=0;function frame(now){requestAnimationFrame(frame);const raw=(now-last)/1000;last=now;const dt=Math.min(raw,.05);if(!paused&&!document.hidden){tick(dt);updateCamera(dt);frameCount++;frameTime+=raw;if(frameCount===180){if(save.quality==='auto'&&frameTime>4.8&&renderer.getPixelRatio()>1){renderer.setPixelRatio(Math.max(.8,renderer.getPixelRatio()-.25));renderer.setSize(innerWidth,innerHeight,false);}frameCount=0;frameTime=0;}renderer.render(scene,camera);}else if(audio.gain)audio.gain.gain.value=0;}
updateMissionUI();updateTraffic(0);updateHUD(MISSIONS[0].stops[0]);drawMap($('minimap'));renderer.render(scene,camera);$('loading').remove();requestAnimationFrame(frame);
if('serviceWorker'in navigator&&import.meta.env.PROD)navigator.serviceWorker.register('/sw.js').catch(()=>{});
// Read-only diagnostics for smoke tests and performance inspection.
window.__valleyDebug=()=>({player:{...player},walking,speed:currentCar.speed,health:currentCar.health,heat,paused,mission:{...run},cash:save.cash,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,pixelRatio:renderer.getPixelRatio(),cars:cars.map(c=>({x:c.x,z:c.z})),version:'1.0.0'});
